name: Build Docker Image and Run Tests in Container

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-run:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t flagcx/flagcx:latest . 

      - name: Run Tests in Docker Container
        run: |
          docker run -d  -it --name flagcx-test --gpus all --privileged --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
          flagcx/flagcx:latest 
          
          docker exec flagcx-test bash -c "chmod +x /workspace/FlagCX/test/scripts/auto_script.sh && /workspace/FlagCX/test/scripts/auto_script.sh"
     
          docker stop flagcx-test
          docker rm flagcx-test
