name: Run Container and Execute Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/cuda:12.4.1-devel-ubuntu22.04
      options:  --privileged --ipc=host --ulimit memlock=-1 --ulimit stack=67108864
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Set up clang-format
        run: |
          apt-get update -y
          apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find . -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -n --style=file

      - name: Check formatting
        run: |
          apt-get install -y git
          git diff --exit-code
        continue-on-error: false  

      - name: Ensure script has execute permissions
        run: chmod +x /__w/FlagCX/FlagCX/test/script/auto_script.sh

      - name: Run Auto Test Script in Container
        run: |
          cd /__w/FlagCX/FlagCX
          ./test/script/auto_script.sh

