name: Run Container and Execute Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    container:
      image:  nvcr.io/nvidia/cuda:12.4.1-devel-ubuntu22.04
      options: --privileged --ipc=host --ulimit memlock=-1 --ulimit stack=67108864

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: false
          set-safe-directory: true


      - name: Set up Python and Install Dependencies
        run: |
          ls
          apt update -y
          apt-get install -y python3 python3-pip python3-venv git
          python3 -m venv venv
          . venv/bin/activate
          cd /__w/FlagCX/FlagCX
          git config --global --add safe.directory /__w/FlagCX/FlagCX
          pip install pre-commit
          pre-commit install

      - name: Run Code Format Check with pre-commit
        run: |
          cd /__w/FlagCX/FlagCX
          . venv/bin/activate
          apt update -y
          apt-get install clang-format -y 
          pre-commit run --all-files
          git diff --exit-code || (
            git add .  
            git commit -m "Auto-format code"  
          )
        continue-on-error: false

      - name: Check the current working directory
        run: |
          echo "Current directory: $(pwd)"
          ls -l ./test/script

      - name: Ensure script has execute permissions
        run: chmod +x /__w/FlagCX/FlagCX/test/script/auto_script.sh

      - name: Run Auto Test Script in Container
        run: |
          cd /__w/FlagCX/FlagCX
          ./test/script/auto_script.sh

